version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WIREBIT_API_KEY=${WIREBIT_API_KEY:-55zoAaEefLMtro18SqGEW6Vmx7x0kwtc}
      - WIREBIT_API_LOGIN=${WIREBIT_API_LOGIN:-FUq0VDBtUVw9t7osngo6ownacyEabfAY}
      - WIREBIT_BASE_URL=${WIREBIT_BASE_URL:-https://wirebit.net/api/userapi/v1/}
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://localhost:3000","http://localhost:5173","http://localhost:5174"]}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
